### ISSUE TITLE
3dskey Mac can't be opened

### ISSUE THREAD

**Issue by espeon** [smartperson/3dskey-Mac#1]
I've got 10.12.3 and it just can't be opened. It just gives me the error shown above.

**Comment by smartperson** [comment]
Do you open the application by double-clicking?

Can you try opening it by right-clicking on it and selecting "Open"? If you are able to, can you check your /Utilities/Console.app to see what relevant error messages (if any) get printed there when you fail to launch 3dskey Mac?
