### ISSUE TITLE
Mac Client not connecting, but detecting.

### ISSUE THREAD

**Issue by Flagers** [smartperson/3dskey-Mac#3]
The client on mac isn't connecting to my 3DS. When I click connect the status turns from (Found 3DS at 192.168.2.2, port 19050) to (Found 3DS at ::ffff:192.168.2.2, port 19050)

**Comment by Ann0ying** [comment]
Same here. I'd really like to use this app.

**Comment by smartperson** [comment]
Hey sorry it's 7 years later, but someone emailed me about this issue and I believe I identified and published a fixed version of the app.
