### ISSUE TITLE
So... the project is dead?

### ISSUE THREAD

**Issue by Ann0ying** [smartperson/3dskey-Mac#4]
I was really excited to use my 3ds as a mac controller. 

Sadly the app wasn't able to connect despite the fact that app was able to find my 3ds. 

I can test, provide any logs and test a lot of games if you wish to continue the project.

**Comment by smartperson** [comment]
Hey sorry it's 7 years later, but someone emailed me about this issue and I believe I identified and published a fixed version of the app.
