### ISSUE TITLE
Cant find .3dsx file in linux version

### ISSUE THREAD

**Issue by SUBLOLLIPOP** [smartperson/3dskey-Mac#5]
In the readme you said that it was based on the homebrew app from the linux version. Well, i cant find the .3dsx file there. What should i do?

**Comment by smartperson** [comment]
This is many years later, sorry, but I have a built .3dsx file in the v0.1.0 tag release of this project. https://github.com/smartperson/3dskey-Mac/releases/tag/v0.1.0
